export const ADD_DROPDOWN_STATE = 'ADD_DROPDOWN_STATE';
export const REMOVE_DROPDOWN_STATE = 'REMOVE_DROPDOWN_STATE';

export const ADD_ITEMS_TO_DROPDOWN = 'ADD_ITEMS_TO_DROPDOWN';

export const LOG_STORED_ITEMS = 'LOG_STORED_ITEMS';
