export const ADD_DROPDOWN_STATE = 'ADD_DROPDOWN_STATE';
export const REMOVE_DROPDOWN_STATE = 'REMOVE_DROPDOWN_STATE';

export const ADD_ITEMS_TO_DROPDOWN = 'ADD_ITEMS_TO_DROPDOWN';

export const LOG_ITEMS_IN_DROPDOWN = 'LOG_ITEMS_IN_DROPDOWN';
